apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rollout-operator-rolebinding
subjects:
  - kind: ServiceAccount
    name: rollout-operator-controller-manager
    namespace: rollout-operator-system
roleRef:
  kind: ClusterRole
  name: rollout-operator-role
  apiGroup: rbac.authorization.k8s.io
