---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.weex.com
  resources:
  - rolloutapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.weex.com
  resources:
  - rolloutapps/finalizers
  verbs:
  - update
- apiGroups:
  - apps.weex.com
  resources:
  - rolloutapps/status
  verbs:
  - get
  - patch
  - update
