# This rule is not used by the project rollout-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the apps.weex.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rollout-operator
    app.kubernetes.io/managed-by: kustomize
  name: rolloutapp-editor-role
rules:
- apiGroups:
  - apps.weex.com
  resources:
  - rolloutapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.weex.com
  resources:
  - rolloutapps/status
  verbs:
  - get
