# This rule is not used by the project rollout-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.weex.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rollout-operator
    app.kubernetes.io/managed-by: kustomize
  name: rolloutapp-admin-role
rules:
- apiGroups:
  - apps.weex.com
  resources:
  - rolloutapps
  verbs:
  - '*'
- apiGroups:
  - apps.weex.com
  resources:
  - rolloutapps/status
  verbs:
  - get
